//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacts
    {
        public int idContact { get; set; }
        public int idUserContact { get; set; }
        public string nameContact { get; set; }
        public string phoneContact { get; set; }
        public string emailContact { get; set; }
        public string informationContact { get; set; }
    
        public virtual user user { get; set; }
    }
}
