//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int fileID { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string type { get; set; }
        public int folderIDFile { get; set; }
    
        public virtual folder folder { get; set; }
    }
}
