//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class historyOrder
    {
        public int idOldOrder { get; set; }
        public int idWorker { get; set; }
        public string FioClient { get; set; }
        public System.DateTime dateCompete { get; set; }
        public string commentClient { get; set; }
        public Nullable<int> rateWorker { get; set; }
        public int statusOrder { get; set; }
    
        public virtual statusOrder statusOrder1 { get; set; }
        public virtual user user { get; set; }
    }
}
