//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personalRoomPsyEntities : DbContext
    {
        public personalRoomPsyEntities()
            : base("name=personalRoomPsyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<contacts> contacts { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<folder> folder { get; set; }
        public virtual DbSet<historyOrder> historyOrder { get; set; }
        public virtual DbSet<lineProblem> lineProblem { get; set; }
        public virtual DbSet<messageProblem> messageProblem { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<statusOrder> statusOrder { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<typeProblem> typeProblem { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<verification> verification { get; set; }
    }
}
