//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int idOrder { get; set; }
        public string FioClient { get; set; }
        public System.DateTime dateMaking { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.TimeSpan timeStart { get; set; }
        public int idProblemOrder { get; set; }
        public int idLineProblemOrder { get; set; }
        public int idWorker { get; set; }
        public int statusOrder { get; set; }
        public string infoFromUserOrder { get; set; }
    
        public virtual lineProblem lineProblem { get; set; }
        public virtual statusOrder statusOrder1 { get; set; }
        public virtual typeProblem typeProblem { get; set; }
        public virtual user user { get; set; }
    }
}
