//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalRoomPsy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.contacts = new HashSet<contacts>();
            this.folder = new HashSet<folder>();
            this.historyOrder = new HashSet<historyOrder>();
            this.messageProblem = new HashSet<messageProblem>();
            this.order = new HashSet<order>();
            this.storage = new HashSet<storage>();
        }
    
        public int idUser { get; set; }
        public string loginUser { get; set; }
        public string passwordUser { get; set; }
        public string fullNameUser { get; set; }
        public System.DateTime dateBirth { get; set; }
        public string emailUser { get; set; }
        public string phoneUser { get; set; }
        public int idRoleUser { get; set; }
        public int countryUser { get; set; }
        public int cityUser { get; set; }
        public string sexUser { get; set; }
        public string urlPhoto { get; set; }
        public Nullable<int> verificationUser { get; set; }
        public Nullable<int> lineWorking { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contacts> contacts { get; set; }
        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<folder> folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historyOrder> historyOrder { get; set; }
        public virtual lineProblem lineProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messageProblem> messageProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage> storage { get; set; }
        public virtual verification verification { get; set; }
    }
}
